# AI黄金交易系统配置文件

# 交易基础配置
trading:
  symbol: "XAUUSD"  # 现货黄金
  timeframe: "1m"   # 1分钟K线
  max_risk: 30      # 最大风险30美元
  position_size: 0.01  # 初始仓位大小
  stop_loss_pips: 50   # 止损点数
  take_profit_pips: 100  # 止盈点数

# 数据源配置
data_sources:
  primary: "yfinance"  # 主要数据源
  backup: "oanda"      # 备用数据源
  update_interval: 60  # 数据更新间隔(秒)
  
# AI模型配置
ai_model:
  type: "ensemble"     # 模型类型: single, ensemble
  models:
    - "random_forest"
    - "xgboost" 
    - "logistic_regression"
  retrain_interval: 168  # 重训练间隔(小时)
  lookback_periods: 100  # 历史数据回看期数
  
# 特征工程配置
features:
  technical_indicators:
    - "sma_5"      # 5期简单移动平均
    - "sma_20"     # 20期简单移动平均
    - "rsi_14"     # 14期RSI
    - "macd"       # MACD
    - "bollinger_bands"  # 布林带
    - "atr_14"     # 14期ATR
  market_sentiment:
    - "vix"        # 恐慌指数
    - "dxy"        # 美元指数
  
# 风险管理配置
risk_management:
  max_daily_loss: 30      # 每日最大亏损
  max_positions: 3        # 最大持仓数
  risk_per_trade: 0.02    # 每笔交易风险比例
  drawdown_limit: 0.15    # 回撤限制
  
# 回测配置
backtest:
  start_date: "2023-01-01"
  end_date: "2024-12-31"
  initial_capital: 10000
  commission: 0.0001     # 手续费
  slippage: 0.0002       # 滑点
  
# 数据库配置
database:
  type: "sqlite"
  path: "data/trading_system.db"
  
# 日志配置
logging:
  level: "INFO"
  file_path: "logs/trading_system.log"
  max_file_size: "10MB"
  backup_count: 5

# API配置
api:
  host: "0.0.0.0"
  port: 8080
  debug: false 